# Generated by Django 5.0.2 on 2024-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gate_way_receive_time', models.DateTimeField()),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('human_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datapoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('serialNumber', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('last_seen', models.IntegerField()),
                ('last_battery_voltage', models.FloatField()),
                ('human_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'devicedata',
                'managed': False,
            },
        ),
    ]
