# Generated by Django 5.0.2 on 2024-02-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery_Voltage_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gateWayReceiveTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=15)),
                ('lastSeen', models.DateField()),
                ('lastBatteryVoltage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Par_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gateWayReceiveTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Relative_Humidity_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gateWayReceiveTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Soil_Electric_Conductivity_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateWayReceiveTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Soil_Relative_Permittivity_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gateWayReceiveTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
