# Generated by Django 5.0.2 on 2024-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil_electric_conductivity_events',
            name='timeStamp',
            field=models.IntegerField(null=True),
        ),
    ]
