# Generated by Django 5.0.2 on 2024-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_soil_temperature_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField()),
                ('gate_way_receive_time', models.DateTimeField()),
                ('device', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('human_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datapoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('serialNumber', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('last_seen', models.IntegerField()),
                ('last_battery_voltage', models.FloatField()),
                ('human_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'devicedata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Battery_Voltage_Events',
        ),
        migrations.DeleteModel(
            name='Device_Data',
        ),
        migrations.DeleteModel(
            name='Par_Events',
        ),
        migrations.DeleteModel(
            name='Relative_Humidity_Events',
        ),
        migrations.DeleteModel(
            name='Soil_Electric_Conductivity_Events',
        ),
        migrations.DeleteModel(
            name='Soil_Relative_Permittivity_Events',
        ),
        migrations.DeleteModel(
            name='soil_temperature_events',
        ),
    ]
